version: '3.6'
services:
  db:
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_HOST_AUTH_METHOD: trust
    image: 'postgres:13-alpine'
    restart: always
    volumes:
      - 'pgdata:/var/lib/postgresql/data'
  web:
    image: 'bitwalker/alpine-elixir-phoenix:latest'
    depends_on:
      - db
    environment:
      MIX_ENV: dev
      DATABASE_HOSTNAME: db
    working_dir: /app
    ports:
      - '4000:4000'
    volumes:
      - ./shorty:/app
    command: bash -c "mix setup && mix phx.server"
volumes:
  pgdata:
